# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Sky/Documents/GUI_Main/mainwidget.ui'
#
# Created: Wed Mar 26 19:13:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(600, 400)
        self.Header = QtGui.QLabel(MainWidget)
        self.Header.setGeometry(QtCore.QRect(0, 10, 600, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Header.setFont(font)
        self.Header.setScaledContents(True)
        self.Header.setAlignment(QtCore.Qt.AlignCenter)
        self.Header.setObjectName("Header")
        self.tabWidget_Main = QtGui.QTabWidget(MainWidget)
        self.tabWidget_Main.setGeometry(QtCore.QRect(0, 70, 601, 331))
        self.tabWidget_Main.setMovable(False)
        self.tabWidget_Main.setObjectName("tabWidget_Main")
        self.Basic = QtGui.QWidget()
        self.Basic.setObjectName("Basic")
        self.InputLabel = QtGui.QLabel(self.Basic)
        self.InputLabel.setGeometry(QtCore.QRect(20, 10, 120, 16))
        self.InputLabel.setObjectName("InputLabel")
        self.InputLabel_Wind_Speed = QtGui.QLineEdit(self.Basic)
        self.InputLabel_Wind_Speed.setGeometry(QtCore.QRect(20, 35, 180, 21))
        self.InputLabel_Wind_Speed.setObjectName("InputLabel_Wind_Speed")
        self.InputLabel_Wind_Direction = QtGui.QLineEdit(self.Basic)
        self.InputLabel_Wind_Direction.setGeometry(QtCore.QRect(20, 60, 180, 21))
        self.InputLabel_Wind_Direction.setObjectName("InputLabel_Wind_Direction")
        self.InputLabel_UAV_Speed = QtGui.QLineEdit(self.Basic)
        self.InputLabel_UAV_Speed.setGeometry(QtCore.QRect(20, 85, 180, 21))
        self.InputLabel_UAV_Speed.setObjectName("InputLabel_UAV_Speed")
        self.InputLabel_UAV_Direction = QtGui.QLineEdit(self.Basic)
        self.InputLabel_UAV_Direction.setGeometry(QtCore.QRect(20, 110, 180, 21))
        self.InputLabel_UAV_Direction.setObjectName("InputLabel_UAV_Direction")
        self.InputLabel_Altitude = QtGui.QLineEdit(self.Basic)
        self.InputLabel_Altitude.setGeometry(QtCore.QRect(20, 135, 180, 21))
        self.InputLabel_Altitude.setObjectName("InputLabel_Altitude")
        self.InputLabel_LD_Ratio = QtGui.QLineEdit(self.Basic)
        self.InputLabel_LD_Ratio.setGeometry(QtCore.QRect(20, 160, 180, 21))
        self.InputLabel_LD_Ratio.setObjectName("InputLabel_LD_Ratio")
        self.OutputLabel = QtGui.QLabel(self.Basic)
        self.OutputLabel.setGeometry(QtCore.QRect(380, 10, 200, 16))
        self.OutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel.setObjectName("OutputLabel")
        self.Button_PlotFlight = QtGui.QPushButton(self.Basic)
        self.Button_PlotFlight.setGeometry(QtCore.QRect(220, 50, 150, 32))
        self.Button_PlotFlight.setObjectName("Button_PlotFlight")
        self.Button_PlotWindContour = QtGui.QPushButton(self.Basic)
        self.Button_PlotWindContour.setGeometry(QtCore.QRect(220, 90, 150, 32))
        self.Button_PlotWindContour.setObjectName("Button_PlotWindContour")
        self.Button_PlotFlightContour = QtGui.QPushButton(self.Basic)
        self.Button_PlotFlightContour.setGeometry(QtCore.QRect(220, 130, 150, 32))
        self.Button_PlotFlightContour.setObjectName("Button_PlotFlightContour")
        self.OutputLabel_Distance = QtGui.QLabel(self.Basic)
        self.OutputLabel_Distance.setGeometry(QtCore.QRect(420, 40, 121, 16))
        self.OutputLabel_Distance.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_Distance.setObjectName("OutputLabel_Distance")
        self.OutputLabel_Heading = QtGui.QLabel(self.Basic)
        self.OutputLabel_Heading.setGeometry(QtCore.QRect(420, 100, 121, 16))
        self.OutputLabel_Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_Heading.setObjectName("OutputLabel_Heading")
        self.OutputLabel_FlightTime = QtGui.QLabel(self.Basic)
        self.OutputLabel_FlightTime.setGeometry(QtCore.QRect(420, 160, 121, 16))
        self.OutputLabel_FlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_FlightTime.setObjectName("OutputLabel_FlightTime")
        self.OutputLabel_ShowFlightTime = QtGui.QLabel(self.Basic)
        self.OutputLabel_ShowFlightTime.setGeometry(QtCore.QRect(420, 190, 121, 16))
        self.OutputLabel_ShowFlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_ShowFlightTime.setObjectName("OutputLabel_ShowFlightTime")
        self.OutputLabel_ShowHeading = QtGui.QLabel(self.Basic)
        self.OutputLabel_ShowHeading.setGeometry(QtCore.QRect(420, 130, 121, 16))
        self.OutputLabel_ShowHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_ShowHeading.setObjectName("OutputLabel_ShowHeading")
        self.OutputLabel_ShowDistance = QtGui.QLabel(self.Basic)
        self.OutputLabel_ShowDistance.setGeometry(QtCore.QRect(420, 70, 121, 16))
        self.OutputLabel_ShowDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel_ShowDistance.setObjectName("OutputLabel_ShowDistance")
        self.tabWidget_Main.addTab(self.Basic, "")
        self.Layer = QtGui.QWidget()
        self.Layer.setObjectName("Layer")
        self.Layer_OutputLabel_Heading = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_Heading.setGeometry(QtCore.QRect(420, 100, 121, 16))
        self.Layer_OutputLabel_Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_Heading.setObjectName("Layer_OutputLabel_Heading")
        self.Layer_OutputLabel_ShowHeading = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_ShowHeading.setGeometry(QtCore.QRect(420, 130, 121, 16))
        self.Layer_OutputLabel_ShowHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_ShowHeading.setObjectName("Layer_OutputLabel_ShowHeading")
        self.Layer_OutputLabel_FlightTime = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_FlightTime.setGeometry(QtCore.QRect(420, 170, 121, 16))
        self.Layer_OutputLabel_FlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_FlightTime.setObjectName("Layer_OutputLabel_FlightTime")
        self.Layer_OutputLabel_ShowFlightTime = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_ShowFlightTime.setGeometry(QtCore.QRect(420, 200, 121, 16))
        self.Layer_OutputLabel_ShowFlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_ShowFlightTime.setObjectName("Layer_OutputLabel_ShowFlightTime")
        self.Layer_OutputLabel_Distance = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_Distance.setGeometry(QtCore.QRect(420, 40, 121, 16))
        self.Layer_OutputLabel_Distance.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_Distance.setObjectName("Layer_OutputLabel_Distance")
        self.Layer_OutputLabel_ShowDistance = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel_ShowDistance.setGeometry(QtCore.QRect(420, 70, 121, 16))
        self.Layer_OutputLabel_ShowDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel_ShowDistance.setObjectName("Layer_OutputLabel_ShowDistance")
        self.Layer_OutputLabel = QtGui.QLabel(self.Layer)
        self.Layer_OutputLabel.setGeometry(QtCore.QRect(380, 10, 200, 16))
        self.Layer_OutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Layer_OutputLabel.setObjectName("Layer_OutputLabel")
        self.Button_RunLayer = QtGui.QPushButton(self.Layer)
        self.Button_RunLayer.setGeometry(QtCore.QRect(50, 100, 150, 32))
        self.Button_RunLayer.setObjectName("Button_RunLayer")
        self.tabWidget_Main.addTab(self.Layer, "")
        self.GFS_1 = QtGui.QWidget()
        self.GFS_1.setObjectName("GFS_1")
        self.GFS1_InputLabel_StartLat = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_StartLat.setGeometry(QtCore.QRect(20, 35, 180, 21))
        self.GFS1_InputLabel_StartLat.setObjectName("GFS1_InputLabel_StartLat")
        self.GFS1_InputLabel = QtGui.QLabel(self.GFS_1)
        self.GFS1_InputLabel.setGeometry(QtCore.QRect(20, 10, 120, 16))
        self.GFS1_InputLabel.setObjectName("GFS1_InputLabel")
        self.GFS1_InputLabel_EndLon = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_EndLon.setGeometry(QtCore.QRect(20, 110, 180, 21))
        self.GFS1_InputLabel_EndLon.setObjectName("GFS1_InputLabel_EndLon")
        self.GFS1_InputLabel_StartTime = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_StartTime.setGeometry(QtCore.QRect(20, 185, 271, 21))
        self.GFS1_InputLabel_StartTime.setObjectName("GFS1_InputLabel_StartTime")
        self.GFS1_InputLabel_EndLat = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_EndLat.setGeometry(QtCore.QRect(20, 85, 180, 21))
        self.GFS1_InputLabel_EndLat.setObjectName("GFS1_InputLabel_EndLat")
        self.GFS1_InputLabel_StartLon = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_StartLon.setGeometry(QtCore.QRect(20, 60, 180, 21))
        self.GFS1_InputLabel_StartLon.setObjectName("GFS1_InputLabel_StartLon")
        self.GFS1_InputLabel_Alt = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_Alt.setGeometry(QtCore.QRect(20, 135, 180, 21))
        self.GFS1_InputLabel_Alt.setObjectName("GFS1_InputLabel_Alt")
        self.GFS1_InputLabel_LD_Ratio = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_LD_Ratio.setGeometry(QtCore.QRect(20, 160, 180, 21))
        self.GFS1_InputLabel_LD_Ratio.setObjectName("GFS1_InputLabel_LD_Ratio")
        self.GFS1_InputLabel_Mass = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_Mass.setGeometry(QtCore.QRect(210, 35, 180, 21))
        self.GFS1_InputLabel_Mass.setObjectName("GFS1_InputLabel_Mass")
        self.GFS1_InputLabel_S = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_S.setGeometry(QtCore.QRect(210, 60, 180, 21))
        self.GFS1_InputLabel_S.setObjectName("GFS1_InputLabel_S")
        self.GFS1_InputLabel_CL = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_CL.setGeometry(QtCore.QRect(210, 85, 180, 21))
        self.GFS1_InputLabel_CL.setObjectName("GFS1_InputLabel_CL")
        self.GFS1_InputLabel_TimeStep1 = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_TimeStep1.setGeometry(QtCore.QRect(210, 110, 180, 21))
        self.GFS1_InputLabel_TimeStep1.setObjectName("GFS1_InputLabel_TimeStep1")
        self.GFS1_InputLabel_TimeStep2 = QtGui.QLineEdit(self.GFS_1)
        self.GFS1_InputLabel_TimeStep2.setGeometry(QtCore.QRect(210, 135, 180, 21))
        self.GFS1_InputLabel_TimeStep2.setObjectName("GFS1_InputLabel_TimeStep2")
        self.GFS1_OutputLabel_Lat = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_Lat.setGeometry(QtCore.QRect(430, 40, 121, 16))
        self.GFS1_OutputLabel_Lat.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_Lat.setObjectName("GFS1_OutputLabel_Lat")
        self.GFS1_OutputLabel_Lon = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_Lon.setGeometry(QtCore.QRect(430, 100, 121, 16))
        self.GFS1_OutputLabel_Lon.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_Lon.setObjectName("GFS1_OutputLabel_Lon")
        self.GFS1_OutputLabel = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel.setGeometry(QtCore.QRect(390, 10, 200, 16))
        self.GFS1_OutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel.setObjectName("GFS1_OutputLabel")
        self.GFS1_OutputLabel_FlightTime = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_FlightTime.setGeometry(QtCore.QRect(430, 160, 121, 16))
        self.GFS1_OutputLabel_FlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_FlightTime.setObjectName("GFS1_OutputLabel_FlightTime")
        self.GFS1_OutputLabel_ShowFlightTime = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_ShowFlightTime.setGeometry(QtCore.QRect(430, 190, 121, 16))
        self.GFS1_OutputLabel_ShowFlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_ShowFlightTime.setObjectName("GFS1_OutputLabel_ShowFlightTime")
        self.GFS1_OutputLabel_ShowLon = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_ShowLon.setGeometry(QtCore.QRect(430, 130, 121, 16))
        self.GFS1_OutputLabel_ShowLon.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_ShowLon.setObjectName("GFS1_OutputLabel_ShowLon")
        self.GFS1_OutputLabel_ShowLat = QtGui.QLabel(self.GFS_1)
        self.GFS1_OutputLabel_ShowLat.setGeometry(QtCore.QRect(430, 70, 121, 16))
        self.GFS1_OutputLabel_ShowLat.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS1_OutputLabel_ShowLat.setObjectName("GFS1_OutputLabel_ShowLat")
        self.Button_GFS1_PlotFlight = QtGui.QPushButton(self.GFS_1)
        self.Button_GFS1_PlotFlight.setGeometry(QtCore.QRect(415, 240, 150, 32))
        self.Button_GFS1_PlotFlight.setObjectName("Button_GFS1_PlotFlight")
        self.GFS1_FigLabel = QtGui.QLabel(self.GFS_1)
        self.GFS1_FigLabel.setGeometry(QtCore.QRect(20, 220, 120, 16))
        self.GFS1_FigLabel.setObjectName("GFS1_FigLabel")
        self.GFS1_Fig_DVT = QtGui.QCheckBox(self.GFS_1)
        self.GFS1_Fig_DVT.setGeometry(QtCore.QRect(20, 240, 110, 20))
        self.GFS1_Fig_DVT.setObjectName("GFS1_Fig_DVT")
        self.GFS1_Fig_AVT = QtGui.QCheckBox(self.GFS_1)
        self.GFS1_Fig_AVT.setGeometry(QtCore.QRect(130, 240, 110, 20))
        self.GFS1_Fig_AVT.setObjectName("GFS1_Fig_AVT")
        self.GFS1_Fig_DVA = QtGui.QCheckBox(self.GFS_1)
        self.GFS1_Fig_DVA.setGeometry(QtCore.QRect(240, 240, 125, 20))
        self.GFS1_Fig_DVA.setObjectName("GFS1_Fig_DVA")
        self.GFS1_Fig_2D = QtGui.QCheckBox(self.GFS_1)
        self.GFS1_Fig_2D.setGeometry(QtCore.QRect(20, 260, 125, 20))
        self.GFS1_Fig_2D.setObjectName("GFS1_Fig_2D")
        self.GFS1_Fig_3D = QtGui.QCheckBox(self.GFS_1)
        self.GFS1_Fig_3D.setGeometry(QtCore.QRect(130, 260, 125, 20))
        self.GFS1_Fig_3D.setObjectName("GFS1_Fig_3D")
        self.tabWidget_Main.addTab(self.GFS_1, "")
        self.GFS_2 = QtGui.QWidget()
        self.GFS_2.setObjectName("GFS_2")
        self.GFS2_Fig_2D = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Fig_2D.setGeometry(QtCore.QRect(20, 230, 125, 20))
        self.GFS2_Fig_2D.setObjectName("GFS2_Fig_2D")
        self.GFS2_OutputLabel_Lat = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_Lat.setGeometry(QtCore.QRect(430, 40, 121, 16))
        self.GFS2_OutputLabel_Lat.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_Lat.setObjectName("GFS2_OutputLabel_Lat")
        self.GFS2_InputLabel_StartLon = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_StartLon.setGeometry(QtCore.QRect(20, 60, 180, 21))
        self.GFS2_InputLabel_StartLon.setObjectName("GFS2_InputLabel_StartLon")
        self.GFS2_OutputLabel_ShowLon = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_ShowLon.setGeometry(QtCore.QRect(430, 130, 121, 16))
        self.GFS2_OutputLabel_ShowLon.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_ShowLon.setObjectName("GFS2_OutputLabel_ShowLon")
        self.GFS2_Fig_3D = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Fig_3D.setGeometry(QtCore.QRect(130, 230, 125, 20))
        self.GFS2_Fig_3D.setObjectName("GFS2_Fig_3D")
        self.GFS2_InputLabel_TimeStep1 = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_TimeStep1.setGeometry(QtCore.QRect(210, 110, 180, 21))
        self.GFS2_InputLabel_TimeStep1.setObjectName("GFS2_InputLabel_TimeStep1")
        self.GFS2_FigLabel = QtGui.QLabel(self.GFS_2)
        self.GFS2_FigLabel.setGeometry(QtCore.QRect(20, 190, 370, 16))
        self.GFS2_FigLabel.setObjectName("GFS2_FigLabel")
        self.GFS2_InputLabel_Alt = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_Alt.setGeometry(QtCore.QRect(20, 85, 180, 21))
        self.GFS2_InputLabel_Alt.setObjectName("GFS2_InputLabel_Alt")
        self.GFS2_InputLabel_StartTime = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_StartTime.setGeometry(QtCore.QRect(20, 160, 370, 21))
        self.GFS2_InputLabel_StartTime.setObjectName("GFS2_InputLabel_StartTime")
        self.GFS2_OutputLabel_FlightTime = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_FlightTime.setGeometry(QtCore.QRect(430, 160, 121, 16))
        self.GFS2_OutputLabel_FlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_FlightTime.setObjectName("GFS2_OutputLabel_FlightTime")
        self.GFS2_InputLabel_TimeStep2 = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_TimeStep2.setGeometry(QtCore.QRect(210, 135, 180, 21))
        self.GFS2_InputLabel_TimeStep2.setObjectName("GFS2_InputLabel_TimeStep2")
        self.GFS2_Fig_DVT = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Fig_DVT.setGeometry(QtCore.QRect(20, 210, 110, 20))
        self.GFS2_Fig_DVT.setObjectName("GFS2_Fig_DVT")
        self.GFS2_InputLabel_LD_Ratio = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_LD_Ratio.setGeometry(QtCore.QRect(20, 110, 180, 21))
        self.GFS2_InputLabel_LD_Ratio.setObjectName("GFS2_InputLabel_LD_Ratio")
        self.GFS2_InputLabel_EndHead = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_EndHead.setGeometry(QtCore.QRect(20, 135, 180, 21))
        self.GFS2_InputLabel_EndHead.setObjectName("GFS2_InputLabel_EndHead")
        self.GFS2_InputLabel_CL = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_CL.setGeometry(QtCore.QRect(210, 85, 180, 21))
        self.GFS2_InputLabel_CL.setObjectName("GFS2_InputLabel_CL")
        self.GFS2_InputLabel_Mass = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_Mass.setGeometry(QtCore.QRect(210, 35, 180, 21))
        self.GFS2_InputLabel_Mass.setObjectName("GFS2_InputLabel_Mass")
        self.GFS2_InputLabel = QtGui.QLabel(self.GFS_2)
        self.GFS2_InputLabel.setGeometry(QtCore.QRect(20, 10, 120, 16))
        self.GFS2_InputLabel.setObjectName("GFS2_InputLabel")
        self.GFS2_Fig_AVT = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Fig_AVT.setGeometry(QtCore.QRect(130, 210, 110, 20))
        self.GFS2_Fig_AVT.setObjectName("GFS2_Fig_AVT")
        self.GFS2_InputLabel_S = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_S.setGeometry(QtCore.QRect(210, 60, 180, 21))
        self.GFS2_InputLabel_S.setObjectName("GFS2_InputLabel_S")
        self.GFS2_InputLabel_StartLat = QtGui.QLineEdit(self.GFS_2)
        self.GFS2_InputLabel_StartLat.setGeometry(QtCore.QRect(20, 35, 180, 21))
        self.GFS2_InputLabel_StartLat.setObjectName("GFS2_InputLabel_StartLat")
        self.GFS2_Fig_DVA = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Fig_DVA.setGeometry(QtCore.QRect(240, 210, 125, 20))
        self.GFS2_Fig_DVA.setObjectName("GFS2_Fig_DVA")
        self.GFS2_OutputLabel_ShowLat = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_ShowLat.setGeometry(QtCore.QRect(430, 70, 121, 16))
        self.GFS2_OutputLabel_ShowLat.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_ShowLat.setObjectName("GFS2_OutputLabel_ShowLat")
        self.GFS2_OutputLabel_ShowFlightTime = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_ShowFlightTime.setGeometry(QtCore.QRect(430, 190, 121, 16))
        self.GFS2_OutputLabel_ShowFlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_ShowFlightTime.setObjectName("GFS2_OutputLabel_ShowFlightTime")
        self.GFS2_OutputLabel_Lon = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_Lon.setGeometry(QtCore.QRect(430, 100, 121, 16))
        self.GFS2_OutputLabel_Lon.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_Lon.setObjectName("GFS2_OutputLabel_Lon")
        self.Button_GFS2_PlotFlight = QtGui.QPushButton(self.GFS_2)
        self.Button_GFS2_PlotFlight.setGeometry(QtCore.QRect(415, 265, 150, 32))
        self.Button_GFS2_PlotFlight.setObjectName("Button_GFS2_PlotFlight")
        self.GFS2_OutputLabel = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel.setGeometry(QtCore.QRect(390, 10, 200, 16))
        self.GFS2_OutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel.setObjectName("GFS2_OutputLabel")
        self.GFS2_OutputLabel_Heading = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_Heading.setGeometry(QtCore.QRect(430, 220, 121, 16))
        self.GFS2_OutputLabel_Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_Heading.setObjectName("GFS2_OutputLabel_Heading")
        self.GFS2_OutputLabel_ShowHeading = QtGui.QLabel(self.GFS_2)
        self.GFS2_OutputLabel_ShowHeading.setGeometry(QtCore.QRect(430, 250, 121, 16))
        self.GFS2_OutputLabel_ShowHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.GFS2_OutputLabel_ShowHeading.setObjectName("GFS2_OutputLabel_ShowHeading")
        self.GFS2_AlgLabel = QtGui.QLabel(self.GFS_2)
        self.GFS2_AlgLabel.setGeometry(QtCore.QRect(20, 255, 370, 16))
        self.GFS2_AlgLabel.setObjectName("GFS2_AlgLabel")
        self.GFS2_Alg_1 = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Alg_1.setGeometry(QtCore.QRect(20, 270, 121, 20))
        self.GFS2_Alg_1.setObjectName("GFS2_Alg_1")
        self.GFS2_Alg_2 = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Alg_2.setGeometry(QtCore.QRect(140, 270, 131, 20))
        self.GFS2_Alg_2.setObjectName("GFS2_Alg_2")
        self.GFS2_Alg_3 = QtGui.QCheckBox(self.GFS_2)
        self.GFS2_Alg_3.setGeometry(QtCore.QRect(270, 270, 131, 20))
        self.GFS2_Alg_3.setObjectName("GFS2_Alg_3")
        self.tabWidget_Main.addTab(self.GFS_2, "")
        self.GFS_3 = QtGui.QWidget()
        self.GFS_3.setObjectName("GFS_3")
        self.GFS3_InputLabel_LD_Ratio = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_LD_Ratio.setGeometry(QtCore.QRect(20, 110, 180, 21))
        self.GFS3_InputLabel_LD_Ratio.setObjectName("GFS3_InputLabel_LD_Ratio")
        self.Button_GFS3_PlotFlight = QtGui.QPushButton(self.GFS_3)
        self.Button_GFS3_PlotFlight.setGeometry(QtCore.QRect(420, 120, 150, 32))
        self.Button_GFS3_PlotFlight.setObjectName("Button_GFS3_PlotFlight")
        self.GFS3_InputLabel_StartLon = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_StartLon.setGeometry(QtCore.QRect(20, 60, 180, 21))
        self.GFS3_InputLabel_StartLon.setObjectName("GFS3_InputLabel_StartLon")
        self.GFS3_InputLabel = QtGui.QLabel(self.GFS_3)
        self.GFS3_InputLabel.setGeometry(QtCore.QRect(20, 10, 120, 16))
        self.GFS3_InputLabel.setObjectName("GFS3_InputLabel")
        self.GFS3_InputLabel_StartTime = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_StartTime.setGeometry(QtCore.QRect(20, 235, 370, 21))
        self.GFS3_InputLabel_StartTime.setObjectName("GFS3_InputLabel_StartTime")
        self.GFS3_InputLabel_CL = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_CL.setGeometry(QtCore.QRect(210, 135, 180, 21))
        self.GFS3_InputLabel_CL.setObjectName("GFS3_InputLabel_CL")
        self.GFS3_InputLabel_Mass = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_Mass.setGeometry(QtCore.QRect(210, 85, 180, 21))
        self.GFS3_InputLabel_Mass.setObjectName("GFS3_InputLabel_Mass")
        self.GFS3_InputLabel_StartHead = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_StartHead.setGeometry(QtCore.QRect(210, 35, 180, 21))
        self.GFS3_InputLabel_StartHead.setObjectName("GFS3_InputLabel_StartHead")
        self.GFS3_InputLabel_S = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_S.setGeometry(QtCore.QRect(210, 110, 180, 21))
        self.GFS3_InputLabel_S.setObjectName("GFS3_InputLabel_S")
        self.GFS3_InputLabel_Alt = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_Alt.setGeometry(QtCore.QRect(20, 85, 180, 21))
        self.GFS3_InputLabel_Alt.setObjectName("GFS3_InputLabel_Alt")
        self.GFS3_InputLabel_TimeStep1 = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_TimeStep1.setGeometry(QtCore.QRect(210, 160, 180, 21))
        self.GFS3_InputLabel_TimeStep1.setObjectName("GFS3_InputLabel_TimeStep1")
        self.GFS3_InputLabel_StartLat = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_StartLat.setGeometry(QtCore.QRect(20, 35, 180, 21))
        self.GFS3_InputLabel_StartLat.setObjectName("GFS3_InputLabel_StartLat")
        self.GFS3_InputLabel_TimeStep2 = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_TimeStep2.setGeometry(QtCore.QRect(210, 185, 180, 21))
        self.GFS3_InputLabel_TimeStep2.setObjectName("GFS3_InputLabel_TimeStep2")
        self.GFS3_InputLabel_EndHead = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_EndHead.setGeometry(QtCore.QRect(210, 60, 180, 21))
        self.GFS3_InputLabel_EndHead.setObjectName("GFS3_InputLabel_EndHead")
        self.GFS3_InputLabel_StartDist = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_StartDist.setGeometry(QtCore.QRect(20, 135, 181, 21))
        self.GFS3_InputLabel_StartDist.setObjectName("GFS3_InputLabel_StartDist")
        self.GFS3_InputLabel_EndDist = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_EndDist.setGeometry(QtCore.QRect(20, 160, 181, 21))
        self.GFS3_InputLabel_EndDist.setObjectName("GFS3_InputLabel_EndDist")
        self.GFS3_InputLabel_DistDiff = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_DistDiff.setGeometry(QtCore.QRect(20, 185, 181, 21))
        self.GFS3_InputLabel_DistDiff.setObjectName("GFS3_InputLabel_DistDiff")
        self.GFS3_InputLabel_Error = QtGui.QLineEdit(self.GFS_3)
        self.GFS3_InputLabel_Error.setGeometry(QtCore.QRect(20, 210, 181, 21))
        self.GFS3_InputLabel_Error.setObjectName("GFS3_InputLabel_Error")
        self.tabWidget_Main.addTab(self.GFS_3, "")

        self.retranslateUi(MainWidget)
        self.tabWidget_Main.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)
        MainWidget.setTabOrder(self.tabWidget_Main, self.InputLabel_Wind_Speed)
        MainWidget.setTabOrder(self.InputLabel_Wind_Speed, self.InputLabel_Wind_Direction)
        MainWidget.setTabOrder(self.InputLabel_Wind_Direction, self.InputLabel_UAV_Speed)
        MainWidget.setTabOrder(self.InputLabel_UAV_Speed, self.InputLabel_UAV_Direction)
        MainWidget.setTabOrder(self.InputLabel_UAV_Direction, self.InputLabel_Altitude)
        MainWidget.setTabOrder(self.InputLabel_Altitude, self.InputLabel_LD_Ratio)
        MainWidget.setTabOrder(self.InputLabel_LD_Ratio, self.Button_PlotFlight)
        MainWidget.setTabOrder(self.Button_PlotFlight, self.Button_PlotWindContour)
        MainWidget.setTabOrder(self.Button_PlotWindContour, self.Button_PlotFlightContour)
        MainWidget.setTabOrder(self.Button_PlotFlightContour, self.Button_RunLayer)
        MainWidget.setTabOrder(self.Button_RunLayer, self.GFS1_InputLabel_StartLat)
        MainWidget.setTabOrder(self.GFS1_InputLabel_StartLat, self.GFS1_InputLabel_StartLon)
        MainWidget.setTabOrder(self.GFS1_InputLabel_StartLon, self.GFS1_InputLabel_EndLat)
        MainWidget.setTabOrder(self.GFS1_InputLabel_EndLat, self.GFS1_InputLabel_EndLon)
        MainWidget.setTabOrder(self.GFS1_InputLabel_EndLon, self.GFS1_InputLabel_Alt)
        MainWidget.setTabOrder(self.GFS1_InputLabel_Alt, self.GFS1_InputLabel_LD_Ratio)
        MainWidget.setTabOrder(self.GFS1_InputLabel_LD_Ratio, self.GFS1_InputLabel_StartTime)
        MainWidget.setTabOrder(self.GFS1_InputLabel_StartTime, self.GFS1_InputLabel_Mass)
        MainWidget.setTabOrder(self.GFS1_InputLabel_Mass, self.GFS1_InputLabel_S)
        MainWidget.setTabOrder(self.GFS1_InputLabel_S, self.GFS1_InputLabel_CL)
        MainWidget.setTabOrder(self.GFS1_InputLabel_CL, self.GFS1_InputLabel_TimeStep1)
        MainWidget.setTabOrder(self.GFS1_InputLabel_TimeStep1, self.GFS1_InputLabel_TimeStep2)
        MainWidget.setTabOrder(self.GFS1_InputLabel_TimeStep2, self.GFS1_Fig_DVT)
        MainWidget.setTabOrder(self.GFS1_Fig_DVT, self.GFS1_Fig_AVT)
        MainWidget.setTabOrder(self.GFS1_Fig_AVT, self.GFS1_Fig_DVA)
        MainWidget.setTabOrder(self.GFS1_Fig_DVA, self.GFS1_Fig_2D)
        MainWidget.setTabOrder(self.GFS1_Fig_2D, self.GFS1_Fig_3D)
        MainWidget.setTabOrder(self.GFS1_Fig_3D, self.Button_GFS1_PlotFlight)
        MainWidget.setTabOrder(self.Button_GFS1_PlotFlight, self.GFS2_InputLabel_StartLat)
        MainWidget.setTabOrder(self.GFS2_InputLabel_StartLat, self.GFS2_InputLabel_StartLon)
        MainWidget.setTabOrder(self.GFS2_InputLabel_StartLon, self.GFS2_InputLabel_Alt)
        MainWidget.setTabOrder(self.GFS2_InputLabel_Alt, self.GFS2_InputLabel_LD_Ratio)
        MainWidget.setTabOrder(self.GFS2_InputLabel_LD_Ratio, self.GFS2_InputLabel_EndHead)
        MainWidget.setTabOrder(self.GFS2_InputLabel_EndHead, self.GFS2_InputLabel_StartTime)
        MainWidget.setTabOrder(self.GFS2_InputLabel_StartTime, self.GFS2_InputLabel_Mass)
        MainWidget.setTabOrder(self.GFS2_InputLabel_Mass, self.GFS2_InputLabel_S)
        MainWidget.setTabOrder(self.GFS2_InputLabel_S, self.GFS2_InputLabel_CL)
        MainWidget.setTabOrder(self.GFS2_InputLabel_CL, self.GFS2_InputLabel_TimeStep1)
        MainWidget.setTabOrder(self.GFS2_InputLabel_TimeStep1, self.GFS2_InputLabel_TimeStep2)
        MainWidget.setTabOrder(self.GFS2_InputLabel_TimeStep2, self.GFS2_Fig_DVT)
        MainWidget.setTabOrder(self.GFS2_Fig_DVT, self.GFS2_Fig_AVT)
        MainWidget.setTabOrder(self.GFS2_Fig_AVT, self.GFS2_Fig_DVA)
        MainWidget.setTabOrder(self.GFS2_Fig_DVA, self.GFS2_Fig_2D)
        MainWidget.setTabOrder(self.GFS2_Fig_2D, self.GFS2_Fig_3D)
        MainWidget.setTabOrder(self.GFS2_Fig_3D, self.GFS2_Alg_1)
        MainWidget.setTabOrder(self.GFS2_Alg_1, self.GFS2_Alg_2)
        MainWidget.setTabOrder(self.GFS2_Alg_2, self.GFS2_Alg_3)
        MainWidget.setTabOrder(self.GFS2_Alg_3, self.Button_GFS2_PlotFlight)
        MainWidget.setTabOrder(self.Button_GFS2_PlotFlight, self.GFS3_InputLabel_StartLat)
        MainWidget.setTabOrder(self.GFS3_InputLabel_StartLat, self.GFS3_InputLabel_StartLon)
        MainWidget.setTabOrder(self.GFS3_InputLabel_StartLon, self.GFS3_InputLabel_Alt)
        MainWidget.setTabOrder(self.GFS3_InputLabel_Alt, self.GFS3_InputLabel_LD_Ratio)
        MainWidget.setTabOrder(self.GFS3_InputLabel_LD_Ratio, self.GFS3_InputLabel_StartDist)
        MainWidget.setTabOrder(self.GFS3_InputLabel_StartDist, self.GFS3_InputLabel_EndDist)
        MainWidget.setTabOrder(self.GFS3_InputLabel_EndDist, self.GFS3_InputLabel_DistDiff)
        MainWidget.setTabOrder(self.GFS3_InputLabel_DistDiff, self.GFS3_InputLabel_Error)
        MainWidget.setTabOrder(self.GFS3_InputLabel_Error, self.GFS3_InputLabel_StartTime)
        MainWidget.setTabOrder(self.GFS3_InputLabel_StartTime, self.GFS3_InputLabel_StartHead)
        MainWidget.setTabOrder(self.GFS3_InputLabel_StartHead, self.GFS3_InputLabel_EndHead)
        MainWidget.setTabOrder(self.GFS3_InputLabel_EndHead, self.GFS3_InputLabel_Mass)
        MainWidget.setTabOrder(self.GFS3_InputLabel_Mass, self.GFS3_InputLabel_S)
        MainWidget.setTabOrder(self.GFS3_InputLabel_S, self.GFS3_InputLabel_CL)
        MainWidget.setTabOrder(self.GFS3_InputLabel_CL, self.GFS3_InputLabel_TimeStep1)
        MainWidget.setTabOrder(self.GFS3_InputLabel_TimeStep1, self.GFS3_InputLabel_TimeStep2)
        MainWidget.setTabOrder(self.GFS3_InputLabel_TimeStep2, self.Button_GFS3_PlotFlight)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(QtGui.QApplication.translate("MainWidget", "UAV Flight Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.Header.setText(QtGui.QApplication.translate("MainWidget", "UAV Flight Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel.setText(QtGui.QApplication.translate("MainWidget", "Input Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_Wind_Speed.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Wind Speed (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_Wind_Direction.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Wind Direction (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_UAV_Speed.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "UAV Speed (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_UAV_Direction.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "UAV Direction (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_Altitude.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Altitude (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.InputLabel_LD_Ratio.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Lift-to-Drag Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel.setText(QtGui.QApplication.translate("MainWidget", "Flight Outputs (For Plot Flight):", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_PlotFlight.setText(QtGui.QApplication.translate("MainWidget", "Plot Flight", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_PlotWindContour.setText(QtGui.QApplication.translate("MainWidget", "Plot Wind Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_PlotFlightContour.setText(QtGui.QApplication.translate("MainWidget", "Plot Flight Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_Distance.setText(QtGui.QApplication.translate("MainWidget", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_Heading.setText(QtGui.QApplication.translate("MainWidget", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_FlightTime.setText(QtGui.QApplication.translate("MainWidget", "Flight Time", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_ShowFlightTime.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_ShowHeading.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputLabel_ShowDistance.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.Basic), QtGui.QApplication.translate("MainWidget", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_Heading.setText(QtGui.QApplication.translate("MainWidget", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_ShowHeading.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_FlightTime.setText(QtGui.QApplication.translate("MainWidget", "Flight Time", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_ShowFlightTime.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_Distance.setText(QtGui.QApplication.translate("MainWidget", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel_ShowDistance.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.Layer_OutputLabel.setText(QtGui.QApplication.translate("MainWidget", "Flight Outputs:", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_RunLayer.setText(QtGui.QApplication.translate("MainWidget", "Run Layer Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.Layer), QtGui.QApplication.translate("MainWidget", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_StartLat.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Latitude (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel.setText(QtGui.QApplication.translate("MainWidget", "Input Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_EndLon.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Desired Longitude (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_StartTime.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Time (e.g 2014,02,02,12,30,01)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_EndLat.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Desired Latitude (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_StartLon.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Longitutde (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_Alt.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Altitude (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_LD_Ratio.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Lift-to-Drag Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_Mass.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Mass (kg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_S.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Planform Area (m^2)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_CL.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Coefficient of Lift", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_TimeStep1.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Above 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_InputLabel_TimeStep2.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Under 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_Lat.setText(QtGui.QApplication.translate("MainWidget", "Final Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_Lon.setText(QtGui.QApplication.translate("MainWidget", "Final Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel.setText(QtGui.QApplication.translate("MainWidget", "Flight Outputs:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_FlightTime.setText(QtGui.QApplication.translate("MainWidget", "Flight Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_ShowFlightTime.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_ShowLon.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_OutputLabel_ShowLat.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_GFS1_PlotFlight.setText(QtGui.QApplication.translate("MainWidget", "Plot Flight", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_FigLabel.setText(QtGui.QApplication.translate("MainWidget", "Figures:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_Fig_DVT.setText(QtGui.QApplication.translate("MainWidget", "Density/Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_Fig_AVT.setText(QtGui.QApplication.translate("MainWidget", "Altitude/Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_Fig_DVA.setText(QtGui.QApplication.translate("MainWidget", "Density/Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_Fig_2D.setText(QtGui.QApplication.translate("MainWidget", "2D Flight Path", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS1_Fig_3D.setText(QtGui.QApplication.translate("MainWidget", "3D Flight Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.GFS_1), QtGui.QApplication.translate("MainWidget", "GFS 1", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Fig_2D.setText(QtGui.QApplication.translate("MainWidget", "2D Flight Path", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_Lat.setText(QtGui.QApplication.translate("MainWidget", "Final Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_StartLon.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Longitutde (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_ShowLon.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Fig_3D.setText(QtGui.QApplication.translate("MainWidget", "3D Flight Path", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_TimeStep1.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Above 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_FigLabel.setText(QtGui.QApplication.translate("MainWidget", "Figures:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_Alt.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Altitude (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_StartTime.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Time e.g 2014,02,02,12,30,01", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_FlightTime.setText(QtGui.QApplication.translate("MainWidget", "Flight Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_TimeStep2.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Under 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Fig_DVT.setText(QtGui.QApplication.translate("MainWidget", "Density/Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_LD_Ratio.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Lift-to-Drag Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_EndHead.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Desired Heading/s e.g. 1,2", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_CL.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Coefficient of Lift", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_Mass.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Mass (kg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel.setText(QtGui.QApplication.translate("MainWidget", "Input Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Fig_AVT.setText(QtGui.QApplication.translate("MainWidget", "Altitude/Time", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_S.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Planform Area (m^2)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_InputLabel_StartLat.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Latitude (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Fig_DVA.setText(QtGui.QApplication.translate("MainWidget", "Density/Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_ShowLat.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_ShowFlightTime.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_Lon.setText(QtGui.QApplication.translate("MainWidget", "Final Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_GFS2_PlotFlight.setText(QtGui.QApplication.translate("MainWidget", "Plot Flight", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel.setText(QtGui.QApplication.translate("MainWidget", "Flight Outputs:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_Heading.setText(QtGui.QApplication.translate("MainWidget", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_OutputLabel_ShowHeading.setText(QtGui.QApplication.translate("MainWidget", "Nil", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_AlgLabel.setText(QtGui.QApplication.translate("MainWidget", "Algorithms:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Alg_1.setText(QtGui.QApplication.translate("MainWidget", "Distance Based", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Alg_2.setText(QtGui.QApplication.translate("MainWidget", "Heading Based 1", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS2_Alg_3.setText(QtGui.QApplication.translate("MainWidget", "Heading Based 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.GFS_2), QtGui.QApplication.translate("MainWidget", "GFS 2", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_LD_Ratio.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Lift-to-Drag Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_GFS3_PlotFlight.setText(QtGui.QApplication.translate("MainWidget", "Plot Flight", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_StartLon.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Longitutde (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel.setText(QtGui.QApplication.translate("MainWidget", "Input Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_StartTime.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Time e.g 2014,02,02,12,30,01", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_CL.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Average Coefficient of Lift", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_Mass.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Mass (kg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_StartHead.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Start Heading (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_S.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Planform Area (m^2)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_Alt.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Altitude (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_TimeStep1.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Above 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_StartLat.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Starting Latitude (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_TimeStep2.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Time Step Under 100m (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_EndHead.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "End Heading (Deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_StartDist.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "First Distance (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_EndDist.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Last Distance (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_DistDiff.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Distance Step (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.GFS3_InputLabel_Error.setPlaceholderText(QtGui.QApplication.translate("MainWidget", "Permissable Error (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.GFS_3), QtGui.QApplication.translate("MainWidget", "GFS 3", None, QtGui.QApplication.UnicodeUTF8))

